-- Generated from rsc/specs/cses_schema_v1.json. Do not edit by hand.
-- Execute only after a verified backup and explicit database-write approval.

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '0';
SELECT pg_advisory_xact_lock(hashtext('cses_public_to_functional_v1'));

-- Begin rsc/sql/cses_schema_v1.sql.
-- CSES functional metadata model v1.
-- This file is a reviewed migration input. Do not execute it outside the approved,
-- backed-up, all-or-nothing database migration transaction.

CREATE SCHEMA IF NOT EXISTS cses_meta;
CREATE SCHEMA IF NOT EXISTS cses_alignment;
CREATE SCHEMA IF NOT EXISTS cses_data;
CREATE SCHEMA IF NOT EXISTS cses_analysis;

CREATE TABLE IF NOT EXISTS cses_meta.cses_survey (
    survey_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_name text NOT NULL UNIQUE,
    survey_wave text NOT NULL UNIQUE,
    nominal_survey_year smallint NOT NULL CHECK (nominal_survey_year BETWEEN 1900 AND 2100),
    country_name text NOT NULL DEFAULT 'Cambodia',
    country_code character(3) NOT NULL DEFAULT 'KHM' CHECK (country_code = 'KHM'),
    release_status text NOT NULL DEFAULT 'baseline'
        CHECK (release_status IN ('discovered', 'baseline', 'reviewed', 'retired')),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cses_meta.cses_source_archive (
    source_archive_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id bigint REFERENCES cses_meta.cses_survey(survey_id) ON DELETE RESTRICT,
    relative_path text NOT NULL UNIQUE,
    sha256 character(64) NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    archive_member_count integer CHECK (archive_member_count >= 0),
    inventory_status text NOT NULL DEFAULT 'inventoried'
        CHECK (inventory_status IN ('discovered', 'inventoried', 'validated', 'unreadable')),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cses_meta.cses_dataset (
    dataset_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_archive_id bigint NOT NULL
        REFERENCES cses_meta.cses_source_archive(source_archive_id) ON DELETE RESTRICT,
    survey_id bigint REFERENCES cses_meta.cses_survey(survey_id) ON DELETE RESTRICT,
    member_path text NOT NULL,
    nested_member_path text NOT NULL DEFAULT '',
    module_code text,
    source_grain text,
    row_count bigint CHECK (row_count >= 0),
    column_count integer CHECK (column_count >= 0),
    read_status text NOT NULL DEFAULT 'discovered'
        CHECK (read_status IN ('discovered', 'readable', 'unreadable', 'excluded')),
    UNIQUE (source_archive_id, member_path, nested_member_path)
);

CREATE TABLE IF NOT EXISTS cses_meta.cses_alignment_release (
    alignment_release_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mapping_version text NOT NULL UNIQUE,
    status text NOT NULL CHECK (status IN ('draft', 'tested', 'approved', 'retired')),
    description text NOT NULL,
    specification_sha256 character(64) CHECK (specification_sha256 ~ '^[0-9a-f]{64}$'),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    approved_at timestamp with time zone,
    CHECK ((status <> 'approved') OR (approved_at IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS cses_meta.cses_storage_table (
    storage_table_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_schema text NOT NULL,
    table_name text NOT NULL,
    object_family text NOT NULL
        CHECK (object_family IN ('final', 'geography', 'source_dictionary', 'alignment_summary')),
    module_code text,
    analytical_grain text,
    natural_key text[] NOT NULL DEFAULT '{}',
    row_count bigint CHECK (row_count >= 0),
    column_count integer CHECK (column_count >= 0),
    relation_fingerprint character(64) CHECK (relation_fingerprint ~ '^[0-9a-f]{64}$'),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (table_schema, table_name)
);

CREATE TABLE IF NOT EXISTS cses_meta.cses_dataset_output (
    dataset_id bigint NOT NULL REFERENCES cses_meta.cses_dataset(dataset_id) ON DELETE RESTRICT,
    storage_table_id bigint NOT NULL
        REFERENCES cses_meta.cses_storage_table(storage_table_id) ON DELETE RESTRICT,
    alignment_release_id bigint
        REFERENCES cses_meta.cses_alignment_release(alignment_release_id) ON DELETE RESTRICT,
    contribution_role text NOT NULL DEFAULT 'source'
        CHECK (contribution_role IN ('source', 'lookup', 'validation')),
    output_row_count bigint CHECK (output_row_count >= 0),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (dataset_id, storage_table_id, contribution_role)
);

CREATE TABLE IF NOT EXISTS cses_meta.cses_load_run (
    load_run_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id bigint REFERENCES cses_meta.cses_survey(survey_id) ON DELETE RESTRICT,
    alignment_release_id bigint
        REFERENCES cses_meta.cses_alignment_release(alignment_release_id) ON DELETE RESTRICT,
    run_scope text NOT NULL,
    source_manifest_sha256 character(64) NOT NULL
        CHECK (source_manifest_sha256 ~ '^[0-9a-f]{64}$'),
    code_git_revision text,
    dvc_revision text,
    status text NOT NULL CHECK (status IN ('running', 'loaded', 'skipped', 'failed', 'rolled_back')),
    row_counts jsonb NOT NULL DEFAULT '{}'::jsonb,
    validation_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
    error_message text,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    finished_at timestamp with time zone,
    CHECK ((status = 'running') OR (finished_at IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS cses_alignment.cses_instrument (
    instrument_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id bigint NOT NULL REFERENCES cses_meta.cses_survey(survey_id) ON DELETE RESTRICT,
    instrument_type text NOT NULL,
    source_file text NOT NULL,
    source_url text,
    source_sha256 character(64) CHECK (source_sha256 ~ '^[0-9a-f]{64}$'),
    document_title text,
    publication_date date,
    language_code text NOT NULL DEFAULT 'und',
    documentation_status text NOT NULL
        CHECK (documentation_status IN ('discovered', 'provisional', 'documented', 'verified')),
    imported_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (survey_id, instrument_type, source_file)
);

CREATE TABLE IF NOT EXISTS cses_alignment.cses_question (
    question_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id bigint NOT NULL
        REFERENCES cses_alignment.cses_instrument(instrument_id) ON DELETE RESTRICT,
    question_code text NOT NULL,
    question_text text,
    section_name text,
    sequence_number integer CHECK (sequence_number > 0),
    source_page integer CHECK (source_page > 0),
    response_options jsonb,
    skip_instruction text,
    question_grain text,
    repeat_context jsonb,
    is_exact_question_text boolean NOT NULL DEFAULT false,
    documentation_status text NOT NULL
        CHECK (documentation_status IN ('discovered', 'provisional', 'documented', 'verified')),
    UNIQUE (instrument_id, question_code)
);

CREATE TABLE IF NOT EXISTS cses_alignment.cses_source_variable (
    source_variable_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id bigint NOT NULL REFERENCES cses_meta.cses_dataset(dataset_id) ON DELETE RESTRICT,
    question_id bigint REFERENCES cses_alignment.cses_question(question_id) ON DELETE SET NULL,
    variable_name text NOT NULL,
    variable_position integer NOT NULL CHECK (variable_position > 0),
    storage_type text,
    variable_label text,
    value_labels jsonb,
    question_link_status text CHECK (question_link_status IN ('proposed', 'reviewed', 'verified')),
    question_link_role text
        CHECK (question_link_role IN ('direct_response', 'standardized_recode', 'recode_copy')),
    alignment_status text NOT NULL DEFAULT 'discovered'
        CHECK (alignment_status IN ('discovered', 'documented', 'mapped', 'tested', 'approved', 'loaded')),
    UNIQUE (dataset_id, variable_name)
);

CREATE TABLE IF NOT EXISTS cses_alignment.cses_canonical_variable (
    canonical_variable_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_table text NOT NULL,
    canonical_name text NOT NULL,
    database_type text NOT NULL,
    measure_type text NOT NULL,
    canonical_definition text NOT NULL,
    analytical_grain text NOT NULL,
    status text NOT NULL DEFAULT 'approved'
        CHECK (status IN ('draft', 'tested', 'approved', 'retired')),
    UNIQUE (target_table, canonical_name)
);

CREATE TABLE IF NOT EXISTS cses_alignment.cses_variable_mapping (
    variable_mapping_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id bigint NOT NULL REFERENCES cses_meta.cses_dataset(dataset_id) ON DELETE RESTRICT,
    canonical_variable_id bigint NOT NULL
        REFERENCES cses_alignment.cses_canonical_variable(canonical_variable_id) ON DELETE RESTRICT,
    alignment_release_id bigint NOT NULL
        REFERENCES cses_meta.cses_alignment_release(alignment_release_id) ON DELETE RESTRICT,
    source_variable_names text[] NOT NULL DEFAULT '{}',
    source_kind text NOT NULL CHECK (source_kind IN ('explicit', 'derived')),
    transformation_rule text NOT NULL,
    alignment_status text NOT NULL CHECK (alignment_status IN ('mapped', 'tested', 'approved', 'loaded')),
    observed_row_count bigint CHECK (observed_row_count >= 0),
    observed_nonnull_count bigint CHECK (observed_nonnull_count >= 0),
    observed_distinct_count bigint CHECK (observed_distinct_count >= 0),
    observation_status text CHECK (observation_status IN ('observed', 'all_null', 'empty_dataset')),
    profiled_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (dataset_id, canonical_variable_id, alignment_release_id)
);

CREATE TABLE IF NOT EXISTS cses_alignment.cses_value_mapping (
    variable_mapping_id bigint NOT NULL
        REFERENCES cses_alignment.cses_variable_mapping(variable_mapping_id) ON DELETE RESTRICT,
    source_value text NOT NULL,
    source_label text,
    canonical_value text,
    canonical_label text,
    alignment_status text NOT NULL CHECK (alignment_status IN ('mapped', 'tested', 'approved', 'loaded')),
    PRIMARY KEY (variable_mapping_id, source_value)
);

CREATE INDEX IF NOT EXISTS idx_cses_survey_year
    ON cses_meta.cses_survey (nominal_survey_year, survey_wave);
CREATE INDEX IF NOT EXISTS idx_cses_dataset_survey_module
    ON cses_meta.cses_dataset (survey_id, module_code);
CREATE INDEX IF NOT EXISTS idx_cses_load_run_status
    ON cses_meta.cses_load_run (status, started_at);
CREATE INDEX IF NOT EXISTS idx_cses_source_variable_status
    ON cses_alignment.cses_source_variable (dataset_id, alignment_status);
CREATE INDEX IF NOT EXISTS idx_cses_source_variable_question
    ON cses_alignment.cses_source_variable (question_id);
CREATE INDEX IF NOT EXISTS idx_cses_variable_mapping_release
    ON cses_alignment.cses_variable_mapping (alignment_release_id);

CREATE OR REPLACE VIEW cses_analysis.cses_storage_inventory AS
SELECT
    storage_table_id,
    table_schema,
    table_name,
    object_family,
    module_code,
    analytical_grain,
    natural_key,
    row_count,
    column_count,
    relation_fingerprint,
    updated_at
FROM cses_meta.cses_storage_table;

CREATE OR REPLACE VIEW cses_analysis.cses_alignment_coverage AS
SELECT
    cv.target_table,
    cv.canonical_name,
    cv.analytical_grain,
    cv.status AS canonical_status,
    count(vm.variable_mapping_id) AS mapping_count,
    count(vm.variable_mapping_id) FILTER (WHERE vm.alignment_status IN ('approved', 'loaded'))
        AS approved_or_loaded_mapping_count,
    count(DISTINCT vm.dataset_id) AS mapped_dataset_count
FROM cses_alignment.cses_canonical_variable AS cv
LEFT JOIN cses_alignment.cses_variable_mapping AS vm USING (canonical_variable_id)
GROUP BY cv.canonical_variable_id;

COMMENT ON SCHEMA cses_meta IS 'CSES survey, source, storage, alignment-release, and load-run registry.';
COMMENT ON SCHEMA cses_alignment IS 'CSES instrument, question, source-variable, and reviewed mapping evidence.';
COMMENT ON SCHEMA cses_data IS 'Authoritative physical CSES survey tables at declared analytical grain.';
COMMENT ON SCHEMA cses_analysis IS 'CSES compatibility, coverage, and quality review interfaces.';
-- End rsc/sql/cses_schema_v1.sql.

CREATE TEMPORARY TABLE cses_migration_plan (
    sequence_number integer PRIMARY KEY,
    relation_name text NOT NULL UNIQUE,
    object_family text NOT NULL,
    target_schema text NOT NULL
) ON COMMIT DROP;

INSERT INTO cses_migration_plan (sequence_number, relation_name, object_family, target_schema)
VALUES
    (1, 'final_HH_CSES', 'final', 'cses_data'),
    (2, 'final_HL_CSES', 'final', 'cses_data'),
    (3, 'final_ED_CSES', 'final', 'cses_data'),
    (4, 'final_HO_CSES', 'final', 'cses_data'),
    (5, 'final_EC_CSES', 'final', 'cses_data'),
    (6, 'final_VL_CSES', 'final', 'cses_data'),
    (7, 'final_SURVEY_DATE_CSES', 'final', 'cses_data'),
    (8, 'dim_geo_CSES', 'geography', 'cses_data'),
    (9, 'ind_que_HH_CSES', 'source_dictionary', 'cses_alignment'),
    (10, 'ind_que_HL_CSES', 'source_dictionary', 'cses_alignment'),
    (11, 'ind_que_ED_CSES', 'source_dictionary', 'cses_alignment'),
    (12, 'ind_que_HO_CSES', 'source_dictionary', 'cses_alignment'),
    (13, 'ind_que_EC_CSES', 'source_dictionary', 'cses_alignment'),
    (14, 'ind_que_VL_CSES', 'source_dictionary', 'cses_alignment'),
    (15, 'ind_que_SURVEY_DATE_CSES', 'source_dictionary', 'cses_alignment'),
    (16, 'align_summary_HH_CSES', 'alignment_summary', 'cses_analysis'),
    (17, 'align_summary_HL_CSES', 'alignment_summary', 'cses_analysis'),
    (18, 'align_summary_ED_CSES', 'alignment_summary', 'cses_analysis'),
    (19, 'align_summary_HO_CSES', 'alignment_summary', 'cses_analysis'),
    (20, 'align_summary_EC_CSES', 'alignment_summary', 'cses_analysis'),
    (21, 'align_summary_VL_CSES', 'alignment_summary', 'cses_analysis'),
    (22, 'align_summary_SURVEY_DATE_CSES', 'alignment_summary', 'cses_analysis');

CREATE TEMPORARY TABLE cses_object_identity_before ON COMMIT DROP AS
SELECT
    plan.relation_name,
    plan.target_schema,
    COALESCE(target.oid, source.oid)::bigint AS physical_oid
FROM cses_migration_plan AS plan
LEFT JOIN pg_catalog.pg_namespace AS source_ns
    ON source_ns.nspname = 'public'
LEFT JOIN pg_catalog.pg_class AS source
    ON source.relnamespace = source_ns.oid
   AND source.relname = plan.relation_name
   AND source.relkind IN ('r', 'p')
LEFT JOIN pg_catalog.pg_namespace AS target_ns
    ON target_ns.nspname = plan.target_schema
LEFT JOIN pg_catalog.pg_class AS target
    ON target.relnamespace = target_ns.oid
   AND target.relname = plan.relation_name
   AND target.relkind IN ('r', 'p');

DO $precondition$
DECLARE
    invalid_count integer;
    plan_count integer;
    public_layout_count integer;
    functional_layout_count integer;
BEGIN
    SELECT count(*) INTO invalid_count
    FROM cses_object_identity_before
    WHERE physical_oid IS NULL;
    IF invalid_count <> 0 THEN
        RAISE EXCEPTION 'CSES migration precondition failed: % physical relations are missing', invalid_count;
    END IF;

    SELECT count(*) INTO invalid_count
    FROM cses_migration_plan AS plan
    LEFT JOIN pg_catalog.pg_namespace AS source_ns
        ON source_ns.nspname = 'public'
    LEFT JOIN pg_catalog.pg_class AS source
        ON source.relnamespace = source_ns.oid AND source.relname = plan.relation_name
    LEFT JOIN pg_catalog.pg_namespace AS target_ns
        ON target_ns.nspname = plan.target_schema
    LEFT JOIN pg_catalog.pg_class AS target
        ON target.relnamespace = target_ns.oid AND target.relname = plan.relation_name
    WHERE NOT (
        (source.relkind IN ('r', 'p') AND target.oid IS NULL)
        OR (source.relkind = 'v' AND target.relkind IN ('r', 'p'))
    );
    IF invalid_count <> 0 THEN
        RAISE EXCEPTION 'CSES migration refuses a missing, conflicting, or mixed layout (% objects)', invalid_count;
    END IF;

    SELECT count(*) INTO plan_count FROM cses_migration_plan;
    SELECT
        count(*) FILTER (WHERE source.relkind IN ('r', 'p') AND target.oid IS NULL),
        count(*) FILTER (WHERE source.relkind = 'v' AND target.relkind IN ('r', 'p'))
    INTO public_layout_count, functional_layout_count
    FROM cses_migration_plan AS plan
    LEFT JOIN pg_catalog.pg_namespace AS source_ns
        ON source_ns.nspname = 'public'
    LEFT JOIN pg_catalog.pg_class AS source
        ON source.relnamespace = source_ns.oid AND source.relname = plan.relation_name
    LEFT JOIN pg_catalog.pg_namespace AS target_ns
        ON target_ns.nspname = plan.target_schema
    LEFT JOIN pg_catalog.pg_class AS target
        ON target.relnamespace = target_ns.oid AND target.relname = plan.relation_name;
    IF NOT (
        (public_layout_count = plan_count AND functional_layout_count = 0)
        OR (public_layout_count = 0 AND functional_layout_count = plan_count)
    ) THEN
        RAISE EXCEPTION
            'CSES migration refuses a mixed layout: public %, functional %, planned %',
            public_layout_count, functional_layout_count, plan_count;
    END IF;
END
$precondition$;

CREATE TEMPORARY TABLE cses_protected_public_before ON COMMIT DROP AS
SELECT c.relname, c.oid::bigint AS relation_oid, c.relkind
FROM pg_catalog.pg_class AS c
JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
WHERE n.nspname = 'public'
  AND c.relkind IN ('r', 'p', 'v', 'm', 'f')
  AND NOT EXISTS (
      SELECT 1 FROM cses_migration_plan AS plan WHERE plan.relation_name = c.relname
  );

DO $move$
DECLARE
    item record;
    source_kind "char";
    target_kind "char";
BEGIN
    FOR item IN SELECT * FROM cses_migration_plan ORDER BY sequence_number LOOP
        SELECT c.relkind INTO source_kind
        FROM pg_catalog.pg_class AS c
        JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relname = item.relation_name;

        SELECT c.relkind INTO target_kind
        FROM pg_catalog.pg_class AS c
        JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
        WHERE n.nspname = item.target_schema AND c.relname = item.relation_name;

        IF source_kind IN ('r', 'p') AND target_kind IS NULL THEN
            EXECUTE format(
                'ALTER TABLE %I.%I SET SCHEMA %I',
                'public', item.relation_name, item.target_schema
            );
        ELSIF source_kind = 'v' AND target_kind IN ('r', 'p') THEN
            NULL;
        ELSE
            RAISE EXCEPTION 'Unexpected state for %: source kind %, target kind %',
                item.relation_name, source_kind, target_kind;
        END IF;
    END LOOP;
END
$move$;

DO $views$
DECLARE
    item record;
    target_owner text;
BEGIN
    FOR item IN SELECT * FROM cses_migration_plan ORDER BY sequence_number LOOP
        EXECUTE format(
            'CREATE OR REPLACE VIEW %I.%I AS SELECT * FROM %I.%I',
            'public', item.relation_name,
            item.target_schema, item.relation_name
        );
        SELECT pg_get_userbyid(c.relowner) INTO target_owner
        FROM pg_catalog.pg_class AS c
        JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
        WHERE n.nspname = item.target_schema AND c.relname = item.relation_name;
        EXECUTE format(
            'ALTER VIEW %I.%I OWNER TO %I',
            'public', item.relation_name, target_owner
        );
        EXECUTE format(
            'COMMENT ON VIEW %I.%I IS %L',
            'public', item.relation_name,
            'Compatibility view; authoritative relation is ' || item.target_schema || '.' || item.relation_name
        );
    END LOOP;
END
$views$;

GRANT SELECT ON "public"."final_HH_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."final_HL_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."final_ED_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."final_HO_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."final_EC_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."final_VL_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."final_SURVEY_DATE_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."dim_geo_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."ind_que_HH_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."ind_que_HL_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."ind_que_ED_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."ind_que_HO_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."ind_que_EC_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."ind_que_VL_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."ind_que_SURVEY_DATE_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."align_summary_HH_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."align_summary_HL_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."align_summary_ED_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."align_summary_HO_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."align_summary_EC_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."align_summary_VL_CSES" TO "mda_readonly";
GRANT SELECT ON "public"."align_summary_SURVEY_DATE_CSES" TO "mda_readonly";

GRANT USAGE ON SCHEMA "cses_alignment" TO "mda_readonly";
GRANT SELECT ON ALL TABLES IN SCHEMA "cses_alignment" TO "mda_readonly";
ALTER DEFAULT PRIVILEGES IN SCHEMA "cses_alignment" GRANT SELECT ON TABLES TO "mda_readonly";
GRANT USAGE ON SCHEMA "cses_analysis" TO "mda_readonly";
GRANT SELECT ON ALL TABLES IN SCHEMA "cses_analysis" TO "mda_readonly";
ALTER DEFAULT PRIVILEGES IN SCHEMA "cses_analysis" GRANT SELECT ON TABLES TO "mda_readonly";
GRANT USAGE ON SCHEMA "cses_data" TO "mda_readonly";
GRANT SELECT ON ALL TABLES IN SCHEMA "cses_data" TO "mda_readonly";
ALTER DEFAULT PRIVILEGES IN SCHEMA "cses_data" GRANT SELECT ON TABLES TO "mda_readonly";
GRANT USAGE ON SCHEMA "cses_meta" TO "mda_readonly";
GRANT SELECT ON ALL TABLES IN SCHEMA "cses_meta" TO "mda_readonly";
ALTER DEFAULT PRIVILEGES IN SCHEMA "cses_meta" GRANT SELECT ON TABLES TO "mda_readonly";

DO $postcondition$
DECLARE
    invalid_count integer;
BEGIN
    SELECT count(*) INTO invalid_count
    FROM cses_object_identity_before AS before
    JOIN cses_migration_plan AS plan USING (relation_name, target_schema)
    LEFT JOIN pg_catalog.pg_namespace AS target_ns ON target_ns.nspname = plan.target_schema
    LEFT JOIN pg_catalog.pg_class AS target
        ON target.relnamespace = target_ns.oid AND target.relname = plan.relation_name
    LEFT JOIN pg_catalog.pg_namespace AS compatibility_ns
        ON compatibility_ns.nspname = 'public'
    LEFT JOIN pg_catalog.pg_class AS compatibility
        ON compatibility.relnamespace = compatibility_ns.oid
       AND compatibility.relname = plan.relation_name
    WHERE target.relkind NOT IN ('r', 'p')
       OR target.oid::bigint IS DISTINCT FROM before.physical_oid
       OR compatibility.relkind IS DISTINCT FROM 'v'::"char";
    IF invalid_count <> 0 THEN
        RAISE EXCEPTION 'CSES migration postcondition failed for % objects', invalid_count;
    END IF;

    SELECT count(*) INTO invalid_count
    FROM (
        (SELECT relname, relation_oid, relkind FROM cses_protected_public_before
         EXCEPT
         SELECT c.relname, c.oid::bigint, c.relkind
         FROM pg_catalog.pg_class AS c
         JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
         WHERE n.nspname = 'public'
           AND c.relkind IN ('r', 'p', 'v', 'm', 'f')
           AND NOT EXISTS (
               SELECT 1 FROM cses_migration_plan AS plan WHERE plan.relation_name = c.relname
           ))
        UNION ALL
        (SELECT c.relname, c.oid::bigint, c.relkind
         FROM pg_catalog.pg_class AS c
         JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
         WHERE n.nspname = 'public'
           AND c.relkind IN ('r', 'p', 'v', 'm', 'f')
           AND NOT EXISTS (
               SELECT 1 FROM cses_migration_plan AS plan WHERE plan.relation_name = c.relname
           )
         EXCEPT
         SELECT relname, relation_oid, relkind FROM cses_protected_public_before)
    ) AS difference;
    IF invalid_count <> 0 THEN
        RAISE EXCEPTION 'A protected public relation changed; rolling back';
    END IF;
END
$postcondition$;

COMMIT;
